version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/facsimile
    depends_on:
      - postgres
    networks:
      - facsimile-network

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=facsimile
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - facsimile-network

networks:
  facsimile-network:
    driver: bridge

volumes:
  postgres-data:
