version: '3.8'

services:
  backend:
    image: yourusername/facsimile-backend:latest
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/facsimile
    depends_on:
      - postgres
    networks:
      - facsimile-network

  frontend:
    image: yourusername/facsimile-frontend:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - facsimile-network

  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=facsimile
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - facsimile-network

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    networks:
      - facsimile-network

networks:
  facsimile-network:
    driver: bridge

volumes:
  postgres-data:
