name: Backend CI

on:
  push:
    paths:
      - 'backend/**'
    branches: [ main ]
  pull_request:
    paths:
      - 'backend/**'
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and test backend
      run: |
        cd backend
        docker build -t backend-test -f Dockerfile.test .
        docker run backend-test

  build:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
        
    - name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push backend
      uses: docker/build-push-action@v4
      with:
        context: ./backend
        push: ${{ github.event_name != 'pull_request' }}
        tags: yourusername/facsimile-backend:latest
